export const arrOfSongs = [
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
    "9000 hiljada",
    "Nisam te zaboravio",
    "Koma",
    "Pokazhi mi shta znash",
    "Mrtvo more",
    "Pijesh sine",
    "Moj je zhivot shvicerska",
  ]